---
title: "clustering - Inconsistent Cluster Size"
output: pdf_document
---

```{r}
library(mvtnorm)
library(scatterplot3d)
library(cluster)
library(MASS)
library(FPDclustering)
library(MixGHD)
library(kernlab)
library(mlbench)
library(dbscan)

set.seed(865)
```

# Convex data with inconsistent cluster size

## No overlapping, 5:2 ratio

```{r}
# convex data with two non-overlapping clusters and inconsistent cluster size

# generate two clusters that are convex, non-overlapping
x1i_1 <- rmvnorm(50,c(0,0,0),sig1_1) # cluster 1, n=50
x1i_2 <- rmvnorm(20,c(8,8,8),sig1_2) # cluster 2, n=10

Xi <- rbind(x1i_1,x1i_2)
           
trueXi <- c(rep(1,50),rep(2,20)) # generate labels for data

scatterplot3d(Xi,color=trueXi,pch=19)
```

```{r Single Linkage 1}
single = agnes(Xi, method = 'single')
plot(single)
scatterplot3d(Xi,color=cutree(single, 2),pch=19)
```

```{r Spectral 1}
spectral <- specc(Xi, centers = 2)
scatterplot3d(Xi, color=spectral, pch=19)
```

```{r DBSCAN 1}
db <- dbscan(Xi, eps=4, minPts = 5)
scatterplot3d(Xi, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 1}
hdb <- hdbscan(Xi, minPts = 7)
scatterplot3d(Xi, color=hdb$cluster +1, pch=19)
```

```{r ARI 1}
print("Single Linkage:")
ARI(trueXi, cutree(single, 4))
print("Spectral Clustering:")
ARI(trueXi, spectral)
print("DBSCAN:")
ARI(trueXi, db$cluster)
print("HDBSCAN:")
ARI(trueXi, hdb$cluster)
```

## No overlapping, small volume and 2:5 ratio
```{r}
# convex data with two non-overlapping clusters and inconsistent cluster size

# generate two clusters that are convex, non-overlapping (sizes flipped)
x1i2_1 <- rmvnorm(20,c(0,0,0),sig1_1) # cluster 1, n=10
x1i2_2 <- rmvnorm(50,c(8,8,8),sig1_2) # cluster 2, n=50

Xi2 <- rbind(x1i2_1,x1i2_2)
           
trueXi2 <- c(rep(1,20),rep(2,50)) # generate labels for data

scatterplot3d(Xi2,color=trueXi2,pch=19)
```

```{r Single Linkage 2}
single = agnes(Xi2, method = 'single')
plot(single)
scatterplot3d(Xi2,color=cutree(single, 2),pch=19)
```

```{r Spectral 2}
spectral <- specc(Xi2, centers = 2)
scatterplot3d(Xi2, color=spectral, pch=19)
```

```{r DBSCAN 2}
db <- dbscan(Xi2, eps=4, minPts = 5)
scatterplot3d(Xi2, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 2}
hdb <- hdbscan(Xi2, minPts = 5)
scatterplot3d(Xi2, color=hdb$cluster +1, pch=19)
```

```{r ARI 2}
print("Single Linkage:")
ARI(trueXi2, cutree(single, 2))
print("Spectral Clustering:")
ARI(trueXi2, spectral)
print("DBSCAN:")
ARI(trueXi2, db$cluster)
print("HDBSCAN:")
ARI(trueXi2, hdb$cluster)
```

## Overlapping, 5:2 ratio

```{r}
# convex data with two overlapping clusters and inconsistent cluster size

# generate two 3d clusters that are convex, overlapping
x2i_1 <- rmvnorm(50,c(-8,8,8),sig2_1) # cluster 1, n=50
x2i_2 <- rmvnorm(20,c(-10,11,11),sig2_2) # cluster 2, n=10

X2i <- rbind(x2i_1,x2i_2)

trueX2i <- c(rep(3,50),rep(4,20))

scatterplot3d(X2i,color=trueX2i,pch=19)
```

```{r Single Linkage 4}
single = agnes(X2i, method = 'single')
plot(single)
scatterplot3d(X2i,color=cutree(single, 3),pch=19)
```

```{r Spectral 4}
spectral <- specc(X2i, centers = 2)
scatterplot3d(X2i, color=spectral, pch=19)
```

```{r DBSCAN 4}
db <- dbscan(X2i, eps=2, minPts = 10)
scatterplot3d(X2i, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 4}
hdb <- hdbscan(X2i, minPts = 7)
scatterplot3d(X2i, color=hdb$cluster +1, pch=19)
```

```{r ARI 4}
print("Single Linkage:")
ARI(trueX2i, cutree(single, 3))
print("Spectral Clustering:")
ARI(trueX2i, spectral)
print("DBSCAN:")
ARI(trueX2i, db$cluster)
print("HDBSCAN:")
ARI(trueX2i, hdb$cluster)
```

## Overlapping with 2:5 ratio

```{r}
# convex data with two overlapping clusters and inconsistent cluster size

# generate two 3d clusters that are convex, overlapping (sizes flipped)
x2i2_1 <- rmvnorm(20,c(-8,8,8),sig2_1) # cluster 1, n=10
x2i2_2 <- rmvnorm(50,c(-10,11,11),sig2_2) # cluster 2, n=50

X2i2 <- rbind(x2i2_1,x2i2_2)

trueX2i2 <- c(rep(3,20),rep(4,50))

scatterplot3d(X2i2,color=trueX2i2,pch=19)
```

```{r Single Linkage 5}
single = agnes(X2i2, method = 'single')
plot(single)
scatterplot3d(X2i2,color=cutree(single, 2),pch=19)
```

```{r Spectral 5}
spectral <- specc(X2i2, centers = 2)
scatterplot3d(X2i2, color=spectral, pch=19)
```

```{r DBSCAN 5}
db <- dbscan(X2i2, eps=2, minPts = 5)
scatterplot3d(X2i2, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 5}
hdb <- hdbscan(X2i2, minPts = 4)
scatterplot3d(X2i2, color=hdb$cluster +1, pch=19)
```

```{r ARI 5}
print("Single Linkage:")
ARI(trueX2i2, cutree(single, 3))
print("Spectral Clustering:")
ARI(trueX2i2, spectral)
print("DBSCAN:")
ARI(trueX2i2, db$cluster)
print("HDBSCAN:")
ARI(trueX2i2, hdb$cluster)
```

# Non-convex data with inconsistent cluster size

##Triple Helix, non overlapping, 20:10:5 ratio:

```{r}
# non-convex data in the shape of a triple helix with three non-overlapping 
# clusters and inconsistent cluster size

t1i <- seq(-1,8*pi,length.out=200) * rnorm(200,mean=1,sd=0.04)
t2i <- seq(-1,8*pi,length.out=100) * rnorm(100,mean=1,sd=0.04)
t3i <- seq(-1,8*pi,length.out=50) * rnorm(50,mean=1,sd=0.04)

# cluster 1, n=200
x3i_1 <- cos(t1i)
x3i_2 <- sin(t1i)
x3i_3 <- t1i * rnorm(200,mean=1,sd=0.01)

# cluster 2, n=100
x3i_4 <- cos(t2i+ 2*pi/3)
x3i_5 <- sin(t2i+ 2*pi/3)
x3i_6 <- t2i * rnorm(100,mean=1,sd=0.01)

# cluster 3, n=50
x3i_7 <- cos(t3i+ 4*pi/3)
x3i_8 <- sin(t3i+ 4*pi/3)
x3i_9 <- t3i * rnorm(50,mean=1,sd=0.01)

X3i_1 <- cbind(x3i_1,x3i_2,x3i_3)
X3i_2 <- cbind(x3i_4,x3i_5,x3i_6)
X3i_3 <- cbind(x3i_7,x3i_8,x3i_9)

X3i <- rbind(X3i_1,X3i_2,X3i_3)

trueX3i <- c(rep(5,200),rep(6,100),rep(7,50))

scatterplot3d(X3i,color=trueX3i,pch=19)
```

```{r Single Linkage 6}
single = agnes(X3i, method = 'single')
plot(single)
scatterplot3d(X3i,color=cutree(single, 2),pch=19)
```

```{r Spectral 6}
spectral <- specc(X3i, centers = 2)
scatterplot3d(X3i, color=spectral, pch=19)
```

```{r DBSCAN 6}
db <- dbscan(X3i, eps=1.5, minPts = 20)
scatterplot3d(X3i, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 6}
hdb <- hdbscan(X3i, minPts = 20)
scatterplot3d(X3i, color=hdb$cluster +1, pch=19)
```

```{r ARI 6}
print("Single Linkage:")
ARI(trueX3i, cutree(single, 3))
print("Spectral Clustering:")
ARI(trueX3i, spectral)
print("DBSCAN:")
ARI(trueX3i, db$cluster)
print("HDBSCAN:")
ARI(trueX3i, hdb$cluster)
```

## Saddle & Spring, overlapping, 40:15 ratio:
```{r}
# non-convex data of a saddle and spring forming overlapping clusters with
# inconsistent cluster size

# simulate data in shape of saddle, cluster 1 n=400
x4i_1 <- runif(400,-4,4)
x4i_2 <- runif(400,-4,4)
x4i_3 <- x4i_1^2 - x4i_2^2

# simulate data in helix shape, cluster 2 n=150
ti <- seq(-10,2*pi,length.out=150) * rnorm(150,mean=1,sd=0.04)

x4i_4 <- cos(ti)
x4i_5 <- sin(ti)
x4i_6 <- ti * rnorm(150,mean=1,sd=0.01)

X4i_1 <- cbind(x4i_1,x4i_2,x4i_3)
X4i_2 <- cbind(x4i_4,x4i_5,x4i_6)

X4i <- rbind(X4i_1,X4i_2)

trueX4i <- c(rep('purple',400),rep('yellow',150))

scatterplot3d(X4i,pch=19,color=trueX4i)
```

```{r Single Linkage 7}
single = agnes(X4i, method = 'single')
plot(single)
scatterplot3d(X4i,color=cutree(single, 2),pch=19)
```

```{r Spectral 7}
spectral <- specc(X4i, centers = 2)
scatterplot3d(X4i, color=spectral, pch=19)
```

```{r DBSCAN 7}
db <- dbscan(X4i, eps=1.5, minPts = 20)
scatterplot3d(X4i, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 7}
hdb <- hdbscan(X4i, minPts = 15)
scatterplot3d(X4i, color=hdb$cluster +1, pch=19)
```

```{r ARI 7}
print("Single Linkage:")
ARI(trueX4i, cutree(single, 3))
print("Spectral Clustering:")
ARI(trueX4i, spectral)
print("DBSCAN:")
ARI(trueX4i, db$cluster)
print("HDBSCAN:")
ARI(trueX4i, hdb$cluster)
```

## Saddle & Spring, overlapping, 15:40 ratio:

```{r}
# non-convex data of a saddle and spring forming two overlapping clusters
# with inconsistent cluster size (sizes flipped)

# simulate data in shape of saddle, cluster 1 n=150
x4i2_1 <- runif(150,-4,4)
x4i2_2 <- runif(150,-4,4)
x4i2_3 <- x4i2_1^2 - x4i2_2^2

# simulate data in helix shape, cluster 2 n=400
ti2 <- seq(-10,2*pi,length.out=400) * rnorm(400,mean=1,sd=0.04)

x4i2_4 <- cos(ti2)
x4i2_5 <- sin(ti2)
x4i2_6 <- ti2 * rnorm(400,mean=1,sd=0.01)

X4i2_1 <- cbind(x4i2_1,x4i2_2,x4i2_3)
X4i2_2 <- cbind(x4i2_4,x4i2_5,x4i2_6)

X4i2 <- rbind(X4i2_1, X4i2_2)

trueX4i2 <- c(rep('purple',150),rep('yellow',400))

scatterplot3d(X4i2,pch=19,color=trueX4i2)
```


```{r Single Linkage 8}
single = agnes(X4i2, method = 'single')
plot(single)
scatterplot3d(X4i2,color=cutree(single, 3),pch=19)
```

```{r Spectral 8}
spectral <- specc(X4i2, centers = 2)
scatterplot3d(X4i2, color=spectral, pch=19)
```

```{r DBSCAN 8}
db <- dbscan(X4i2, eps=1.5, minPts = 50)
scatterplot3d(X4i2, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 8}
hdb <- hdbscan(X4i2, minPts = 30)
scatterplot3d(X4i2, color=hdb$cluster +1, pch=19)
```

```{r ARI 8}
print("Single Linkage:")
ARI(trueX4i2, cutree(single, 3))
print("Spectral Clustering:")
ARI(trueX4i2, spectral)
print("DBSCAN:")
ARI(trueX4i2, db$cluster)
print("HDBSCAN:")
ARI(trueX4i2, hdb$cluster)
```