---
title: "clustering - Consistent Cluster Size"
date: "2026-04-30"
output: pdf_document
---

```{r}
library(mvtnorm)
library(scatterplot3d)
library(cluster)
library(MASS)
library(FPDclustering)
library(MixGHD)
library(kernlab)
library(mlbench)
library(dbscan)

set.seed(865)
```

# Convex data with consistent cluster size

```{r}
# convex data with two non-overlapping clusters and consistent cluster size

# generate two clusters that are convex, non-overlapping
sig1_1 <- diag(3)
sig1_2 <- diag(6.25,3)
x1_1 <- rmvnorm(50,c(0,0,0),sig1_1)
x1_2 <- rmvnorm(50,c(8,8,8),sig1_2)

X <- rbind(x1_1,x1_2)
           
trueX <- rep(1:2,each=50) # generate labels for data

scatterplot3d(X,color=trueX,pch=19)
```

```{r Single Linkage 1}
single = agnes(X, method = 'single')
plot(single)
scatterplot3d(X,color=cutree(single, 3),pch=19)
```

```{r Spectral 1}
spectral <- specc(X, centers = 2)
scatterplot3d(X, color=spectral, pch=19)
```

```{r DBSCAN 1}
db <- dbscan(X, eps=5, minPts = 20)
scatterplot3d(X, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 1}
hdb <- hdbscan(X, minPts = 20)
scatterplot3d(X, color=hdb$cluster +1, pch=19)
```

```{r ARI 1}
print("Single Linkage:")
ARI(trueX, cutree(single, 3))
print("Spectral Clustering:")
ARI(trueX, spectral)
print("DBSCAN:")
ARI(trueX, db$cluster)
print("HDBSCAN:")
ARI(trueX, hdb$cluster)
```

```{r}
# convex data with two overlapping clusters and consistent cluster size

# generate two 3d clusters that are convex, overlapping
sig2_1 <- diag(6,3)
sig2_2 <- diag(0.75,3)
x2_1 <- rmvnorm(50,c(-9,9,9),sig2_1)
x2_2 <- rmvnorm(50,c(-10,11,11),sig2_2)

X2 <- rbind(x2_1,x2_2)

trueX2 <- rep(3:4,each=50)

scatterplot3d(X2,color=trueX2,pch=19)
```

```{r Single 2}
single = agnes(X2, method = 'single')
plot(single)
scatterplot3d(X2,color=cutree(single, 5),pch=19)
```
```{r Spectral 2}
spectral <- specc(X2, centers = 2)
scatterplot3d(X2, color=spectral, pch=19)
```

```{r DBSCAN 2}
db <- dbscan(X2, eps=2, minPts = 25)
scatterplot3d(X2, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 2}
hdb <- hdbscan(X2, minPts = 3)
scatterplot3d(X2, color=hdb$cluster +1, pch=19)
```
```{r ARI 2}
print("Single Linkage:")
ARI(trueX2, cutree(single, 3))
print("Spectral Clustering:")
ARI(trueX2, spectral)
print("DBSCAN:")
ARI(trueX2, db$cluster)
print("HDBSCAN:")
ARI(trueX2, hdb$cluster)
```

# Non-convex data with consistent cluster size

```{r}
# non-convex data in the shape of a triple helix with three non-overlapping 
# clusters and consistent cluster size

t <- seq(-1,8*pi,length.out=200) * rnorm(200,mean=1,sd=0.04)

# cluster 1
x3_1 <- cos(t)
x3_2 <- sin(t)
x3_3 <- t * rnorm(200,mean=1,sd=0.01)

# cluster 2
x3_4 <- cos(t+ 2*pi/3)
x3_5 <- sin(t+ 2*pi/3)
x3_6 <- t * rnorm(200,mean=1,sd=0.01)

# cluster 3
x3_7 <- cos(t+ 4*pi/3)
x3_8 <- sin(t+ 4*pi/3)
x3_9 <- t * rnorm(200,mean=1,sd=0.01)

X3_1 <- cbind(x3_1,x3_2,x3_3)
X3_2 <- cbind(x3_4,x3_5,x3_6)
X3_3 <- cbind(x3_7,x3_8,x3_9)

X3 <- rbind(X3_1,X3_2,X3_3)

trueX3 <- rep(5:7,each=200)

scatterplot3d(X3,color=trueX3,pch=19)
```

```{r Single 3}
single = agnes(X3, method = 'single')
plot(single)
scatterplot3d(X3,color=cutree(single, 3),pch=19)
```

```{r Spectral 3}
spectral <- specc(X3, centers = 3)
scatterplot3d(X3, color=spectral, pch=19)
```

```{r DBSCAN 3}
db <- dbscan(X3, eps=1.5, minPts = 30)
scatterplot3d(X3, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 3}
hdb <- hdbscan(X3, minPts = 40)
scatterplot3d(X3, color=hdb$cluster +1, pch=19)
```
```{r ARI 3}
print("Single Linkage:")
ARI(trueX3, cutree(single, 8))
print("Spectral Clustering:")
ARI(trueX3, spectral)
print("DBSCAN:")
ARI(trueX3, db$cluster)
print("HDBSCAN:")
ARI(trueX3, hdb$cluster)
```
```{r}
# non-convex data of a saddle and spring forming two overlapping clusters
# with consistent cluster size, n=500

# simulate data in shape of saddle, cluster 1
x4_1 <- runif(500,-3,3)
x4_2 <- runif(500,-3,3)
x4_3 <- x4_1^2 - x4_2^2

# simulate data in helix shape, cluster 2
t <- seq(-10,2*pi,length.out=500) * rnorm(500,mean=1,sd=0.04)

x4_4 <- cos(t)
x4_5 <- sin(t)
x4_6 <- t * rnorm(500,mean=1,sd=0.01)

X4_1 <- cbind(x4_1,x4_2,x4_3)
X4_2 <- cbind(x4_4,x4_5,x4_6)

X4 <- rbind(X4_1,X4_2)

trueX4 <- rep(c('purple','yellow'),each=500)

scatterplot3d(X4,pch=19,color=trueX4)
```

```{r Single 4}
single = agnes(X4, method = 'single')
plot(single)
scatterplot3d(X4,color=cutree(single, 4),pch=19)
```

```{r Spectral 4}
spectral <- specc(X4, centers = 2)
scatterplot3d(X4, color=spectral, pch=19)
```

```{r DBSCAN 4}
db <- dbscan(X4, eps=0.8, minPts = 30)
scatterplot3d(X4, color=db$cluster +1, pch=19)
```

```{r HDBSCAN 4}
hdb <- hdbscan(X4, minPts = 50)
scatterplot3d(X4, color=hdb$cluster +1, pch=19)
```
```{r ARI 4}
print("Single Linkage:")
ARI(trueX4, cutree(single, 8))
print("Spectral Clustering:")
ARI(trueX4, spectral)
print("DBSCAN:")
ARI(trueX4, db$cluster)
print("HDBSCAN:")
ARI(trueX4, hdb$cluster)
```
