---
title: "clustering - Inconsistent Cluster Size"
output: pdf_document
---

```{r}
library(mvtnorm)
library(scatterplot3d)
library(cluster)
library(kernlab)
library(dbscan)

set.seed(865)

source("functions.R")
source("datasim.R")
```

# Convex data with inconsistent cluster size

## No overlapping, 5:2 ratio

```{r}
# convex data with two non-overlapping clusters and inconsistent cluster size
scatterplot3d(Xi,color=trueXi,pch=19)
```

```{r}
out <- run_methods(Xi, trueXi, k = 2)
out$results
```

## No overlapping, 2:5 ratio
```{r}
# convex data with two non-overlapping clusters and inconsistent cluster size
scatterplot3d(Xi2,color=trueXi2,pch=19)
```

```{r}
out <- run_methods(Xi2, trueXi2, k = 2)
out$results
```

## Overlapping, 5:2 ratio

```{r}
# convex data with two overlapping clusters and inconsistent cluster size
scatterplot3d(X2i,color=trueX2i,pch=19)
```

```{r}
out <- run_methods(X2i, trueX2i, k = 2,
                   hdb_minPts = 10)
out$results
```

## Overlapping with 2:5 ratio

```{r}
# convex data with two overlapping clusters and inconsistent cluster size
scatterplot3d(X2i2,color=trueX2i2,pch=19)
```

```{r}
out <- run_methods(X2i2, trueX2i2, k = 2,
                   hdb_minPts = 6)
out$results
```

# Non-convex data with inconsistent cluster size

##Triple Helix, non overlapping, 500:200:100 ratio:

```{r}
# non-convex data in the shape of a triple helix with three non-overlapping 
# clusters and inconsistent cluster size
scatterplot3d(X3i,color=trueX3i,pch=19)
```

```{r}
out <- run_methods(X3i, trueX3i, k = 3)
out$results
```

## Saddle & Spring, overlapping, 400:150 ratio:
```{r}
# non-convex data of a saddle and spring forming overlapping clusters with
# inconsistent cluster size
scatterplot3d(X4i,pch=19,color=trueX4i)
```
```{r}
out <- run_methods(X4i, trueX4i, k = 2)
out$results
```

## Saddle & Spring, overlapping, 150:400 ratio:

```{r}
# non-convex data of a saddle and spring forming two overlapping clusters
# with inconsistent cluster size (sizes flipped)
scatterplot3d(X4i2,pch=19,color=trueX4i2)
```

```{r}
out <- run_methods(X4i2, trueX4i2, k = 2)
out$results
```